# Generated by Django 4.1 on 2022-09-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppsServicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='tiempo',
            field=models.CharField(max_length=128),
        ),
    ]
